from .client_form import *
from .order_form import *
from .product_form import *
from .allowance_discount_form import *
from .complication_element_form import *
from .fabric_form import *
from .minimal_style_form import *
from .atelier_form import *
from .signup_form import *
from .seamstress_sign_up_form import *
from .tailor_sign_up_form import *
from .profile_form import *
