from .index import *
from .client_view import *
from .product_view import *
from .order_view import *
from .minimal_style_view import *
from .fabric_view import *
from .complication_element_view import *
from .allowance_discount_view import *
from .atelier_view import *
from .profile_view import *
from .signup_view import *
from .seamstress_view import *
from .tailor_view import *
