# Generated by Django 2.2.3 on 2019-09-23 09:13

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AllowanceDiscount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name')),
                ('coefficient', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='coefficient')),
                ('label', models.CharField(max_length=255, verbose_name='group')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30, verbose_name='first Name')),
                ('last_name', models.CharField(max_length=30, verbose_name='second Name')),
                ('tel_number', models.CharField(blank=True, max_length=30, verbose_name='tel. number')),
                ('place', models.CharField(max_length=30, verbose_name='place')),
            ],
            options={
                'ordering': ['first_name'],
            },
        ),
        migrations.CreateModel(
            name='ComplicationElement',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, verbose_name='name')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=5, verbose_name='base price')),
                ('complexity', models.DecimalField(decimal_places=2, default=1, max_digits=3, verbose_name='complexity')),
                ('group', models.CharField(default='4', max_length=255, verbose_name='group name')),
            ],
            options={
                'ordering': ['group'],
            },
        ),
        migrations.CreateModel(
            name='Fabric',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, verbose_name='name')),
                ('group', models.CharField(choices=[('GR0', 'Група 0'), ('GR1', 'Група І'), ('GR2', 'Група ІІ'), ('GR3', 'Група ІІІ'), ('GR4', 'Група ІV')], default='GR2', max_length=3, verbose_name='group')),
                ('complexity_factor', models.DecimalField(decimal_places=2, default=1, max_digits=5, verbose_name='complexity factor')),
            ],
            options={
                'ordering': ['group'],
            },
        ),
        migrations.CreateModel(
            name='MinimalStyle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(max_length=264, verbose_name='name')),
                ('group', models.CharField(max_length=264, verbose_name='product group')),
            ],
            options={
                'ordering': ['group'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264, verbose_name='name')),
                ('base_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='base price')),
                ('minimal_style', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atelier.MinimalStyle', verbose_name='minimal style')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('processing_category', models.CharField(choices=[('1', 'Processing category 1'), ('2', 'Processing category 2')], default='2', max_length=1, verbose_name='processing category')),
                ('order_date', models.DateField(default=datetime.date.today, verbose_name='order date')),
                ('allowance_discount', models.ManyToManyField(blank=True, to='atelier.AllowanceDiscount', verbose_name='allowance/discount')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atelier.Client', verbose_name='client')),
                ('complication_elements', models.ManyToManyField(blank=True, to='atelier.ComplicationElement', verbose_name='complication elements')),
                ('fabric', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atelier.Fabric', verbose_name='fabric')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='atelier.Product', verbose_name='product')),
            ],
            options={
                'ordering': ['order_date'],
            },
        ),
    ]
