# Generated by Django 2.2.3 on 2019-11-11 07:37

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('atelier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='deadline',
            field=models.DateField(blank=True, default=datetime.date(2019, 11, 25), null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='tailor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='fabric',
            name='group',
            field=models.CharField(choices=[('GR0', 'Group 0'), ('GR1', 'Group I'), ('GR2', 'Group II'), ('GR3', 'Group III'), ('GR4', 'Group IV')], default='GR2', max_length=3, verbose_name='group'),
        ),
    ]
